### PR TITLE
Add npm script to start tests in watch mode

### PR DESCRIPTION
**Pull request by beeman**
### Description

Added a script to run the test in watch mode.

Originally came with the PR #11 but is now separate. 
#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [n/a] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@beeman, your PR needs to rebase, probably because your other PR just landed.

**Review by b-admike — APPROVED** [review]

**Comment by beeman** [comment]
@dhmlau done! 👍

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@beeman, thanks for your PR.  It's landed!

**Pull request merged**
